name: Deploy Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
      HCAPTCHA_SECRET: ${{ secrets.HCAPTCHA_SECRET }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase secrets set HCAPTCHA_SECRET=HCAPTCHA_SECRET
      - run: supabase functions deploy --project-ref $SUPABASE_PROJECT_ID --no-verify-jwt
